# Generated by Django 3.1.1 on 2022-02-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0002_auto_20220207_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
