# Generated by Django 3.1.1 on 2022-02-07 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0005_auto_20220207_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/', verbose_name='upload a video'),
            preserve_default=False,
        ),
    ]
